app/connectors/ResidencyStatusAPIConnector.scala
app/controllers/DashboardController.scala

updated due to the bug
https://github.com/playframework/playframework/issues/6750

RAS-642- controller method to download results file

---

app/views/helpers/rasInput.scala.html
app/views/member_dob.scala.html

Added types to member_dob page

Added input type method in rasinput

---

app/views/upload_result.scala.html
test/controllers/WhatDoYouWantToDoControllerSpec.scala

Added tabindex=-1 to icon--image
Removed unit tests

Removed href from icon--image

---

app/views/file_upload.scala.html
app/views/helpers/errorSummary.scala.html

set datafocus on fileupload page to fileupload choose a file

removed tooltips

---

app/views/member_dob.scala.html

removed maxlength from memberdateofbirth page input

changed type number to type tel on memberdateofbirth page

---

app/views/match_not_found.scala.html
test/controllers/ResultsControllerSpec.scala

added ga events for look up another member link
added link to view

added unit tests for look up another member link

---

app/config/ApplicationConfig.scala
app/config/FrontendGlobal.scala
app/config/FrontendWiring.scala
app/config/SessionCacheWiring.scala
app/connectors/ContactFrontendConnector.scala
app/connectors/FileUploadConnector.scala
app/connectors/ResidencyStatusAPIConnector.scala
app/connectors/UserDetailsConnector.scala
app/controllers/ChooseAnOptionController.scala
app/controllers/RasResidencyCheckerController.scala
app/controllers/ResultsController.scala
app/services/AuditService.scala
app/services/TaxYearResolver.scala
project/FrontendBuild.scala
project/plugins.sbt
test/connectors/ContactFronetendConnectorSpec.scala
test/connectors/FileUploadConnectorSpec.scala
test/connectors/ResidencyStatusAPIConnectorSpec.scala
test/controllers/ChooseAnOptionControllerSpec.scala
test/controllers/ResultsControllerSpec.scala
test/services/TaxYearResolverSpec.scala

Upgrades for play 2.5.19 enforcement and library upgrades

DDCNOS-3602: Upgrade RAS-Frontend to Play 2.5.19

---

conf/messages

DDCNLS-4565: Remove contractions

---

conf/messages

@Muhammad-Ali-Ahmad – I've removed single primes which wouldn't display anyway. Can you check my code - unit tests were okay. Thanks

DDCNLS-4566: Remove single primes which don't show up

---

conf/application.conf

DDCNL-1335: Adding config to match ensure application behaves like PROD

---

conf/messages

##Bug fix / New feature (delete as appropriate)
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

DDCE450:error messages updated

---

conf/messages
public/javascript/check-file-type.js

Updated error messages for upload-a-file as mentioned under the ticket.

DDCE-459 updated error messages for upload-a-file

---

app/views/match_not_found.scala.html

##New feature
Changes to Check answer page
Left hand side column text made as **Bold**

DDCE-455 Changes to check answer page

---

app/views/match_not_found.scala.html

Updated HTML file for successful Unit test

Updated html for successful unit test

---

app/views/cannot_upload_another_file.scala.html
conf/messages
test/controllers/FileUploadControllerSpec.scala

##New feature
Changed content of Title and H1 on /cannot-upload-another-file page. And removed a paragraph. As mentioned in the ticket.
There are no acceptance tests for this page so no changes are required in Acceptance tests (Confirmed with Dan)

DDCE-465 changes content on cannot-upload-another-file page

---

app/controllers/FileUploadController.scala

##Bug fix
Fix for incorrect redirection

DDCE-458: Moving file upload validation to back end (fix)

---

app/controllers/FileUploadController.scala
app/views/match_not_found.scala.html
conf/application.conf

##Bug fix
More fixes for failing journey tests in dev environment

DDCE-458: Moving file upload validation to back end (fix2)

---

app/views/file_upload.scala.html
project/AppDependencies.scala
public/javascript/check-file-type.js

Re-enables the continue button on /upload-a-file when the user chooses a different file to upload.
To view this page locally you need to temporarily replace Line 84 in FileUploadController Future.successful(Redirect(routes.ErrorController.renderGlobalErrorPage())) with:
Future.successful(Ok(views.html.file_upload("","")))
Link to acceptance test PR https://github.com/hmrc/ras-acceptance-tests/pull/72 …

DDCE-458: Continue button is re-enabled once a new file is uploaded

---

conf/messages

Changed content of the end of the last paragraph on page /residency-status-added 
No changes in Acceptance tests.
Units tests are already covered.

DDCE-529 changed content on /residency-status-added page

---

app/controllers/RasResidencyCheckerController.scala
conf/messages
test/controllers/RasResidencyCheckerControllerSpec.scala

##New feature
Content change on /member-residency-status page in the confirmation box

DDCE-527 Content change on /member-residency-status page

---

test/forms/MemberDateOfBirthFormSpec.scala
test/forms/MemberNinoFormSpec.scala

##Bug fix / New feature (delete as appropriate)
I made a last minute change to the forms because of some acceptance test failures and forgot to update the unit test to match.

DDCE-198: Unit test fix

---

app/views/file_upload.scala.html

##UI Journey tests fix
Journey tests passed locally due to them not running the full suite until environments. Id change to match a change made in the AT repo here - https://github.com/hmrc/ras-acceptance-tests/commit/803c8ef7b81b45506b6b28f6dbf602043e527fd9

DDCE-198: UI Journey test fix

---

public/stylesheets/ras.css

##New feature (delete as appropriate)
1. Colour chnage for confirmation page
2. No change to any other repo

DDCE-457 Colour chnage for confirmation page

---

app/services/SessionService.scala
project/AppDependencies.scala
project/plugins.sbt

##Spike
Log change to prevent confusion while monitoring. More info here: - - https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=200808823

DDCE-433: Log change, dependency update

---

.github/PULL_REQUEST_TEMPLATE.md
conf/application.conf
project/AppDependencies.scala

Added config required for accessibility statement footer link. 
See here for acceptance test PR: https://github.com/hmrc/ras-acceptance-tests/pull/78

[DP][DDCE-992]: Added url for Accessibility statement footer link

---

app/config/ApplicationConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

Implemented GTM snipped to help assist migration from GA. 

[EH][DDCE-1078] Implemented GTM

---

app/controllers/ChooseAnOptionController.scala

During exploratory testing, it was found that after uploading a file to ras-frontend, if the file is still processing then the frontend displays a message that includes a curly bracket that is not required. For example:
File uploaded today at 10:44am}.
To resolve the issue an extra curly brace was removed from the controller.
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met? Yes
- Have you done a visual check of the changes? Yes
- Is there any still commented or unused code? Lingering printlns? No
- Have things been implemented in a complicated way? N/a
- Are the test still over the coverage threshold? N/a
- Does the compiler throw a lot of warnings? No
- Have methods and tests been named clearly? Yes
- Were there any changes in the config? Do changes …

DDCE-1192:ras-frontend showing incorrect curly bracket

---

app/config/ApplicationConfig.scala
app/controllers/RasController.scala
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt

DDCE-1297: Removing references to deprecated CA_FRONTEND

---

conf/application.conf

[EH][DDCE-1316] Changed GTM id to N/A so we can manage in configs

---

public/stylesheets/ras.css

As we're on old assets we had to take the CSS from [the gds](https://design-system.service.gov.uk/components/text-input/) and incorporate it into our custom CSS. No test changes required

[DP][DDCE-1447]: Added thick border for focussed inputs

---

build.sbt
conf/messages

Added text for screen readers to know link will open in a new tab.

DDCE-1448: Accessibility text added for opening link in new tab

---

app/connectors/ResidencyStatusAPIConnector.scala
app/controllers/FileUploadController.scala
build.sbt
conf/application.conf

We were sending the delete request with 2 `//` in the url which was getting a 404 every time from the backend which mean it was not deleting the files correctly. 
Also some app config cleanup
Somewhat linked PR to fix other issues with file deletion on ras-api: https://github.com/hmrc/ras-api/pull/186

[DP][DDCE-925]: Remove duplicate '/' from deletion url

---

app/config/ApplicationConfig.scala
app/views/govuk_wrapper.scala.html
build.sbt
conf/application.conf
test/utils/RasTestHelper.scala

Migrated GTM to tracking consent frontend.
**PRs to merge prior to this**
Addition of tracking consent frontend to SM profile: https://github.com/hmrc/service-manager-config/pull/3308
Removal of GTM from Staging: https://github.com/hmrc/app-config-staging/pull/7589
Removal of GA from QA: https://github.com/hmrc/app-config-qa/pull/10526

[EH][DDCE-1588] Added the tracking consent snippet

---

app/views/govuk_wrapper.scala.html
public/javascript/check-file-type.js
public/javascript/ras.js

Pipeline failed after removing GA config from QA. It was found that there is existing GA JS within ras-frontend which could be the cause of the test failure.

[EH][DDCE-1588] Removed GA JS

---

app/connectors/ResidencyStatusAPIConnector.scala

Too many headers make request fail. Less headers more good

[DP][DDCE-1499] Remove superfluous headers

---

app/views/choose_an_option.scala.html
public/stylesheets/ras.css
test/views/ChooseAnOptionViewSpec.scala

Small class change to landing page task list headers to make them GDS compliant. Signed off by design team.

[DDCE-2183][EH] Updated task list headers for GDS compliance

---

app/views/file_upload.scala.html
app/views/match_not_found.scala.html
app/views/upload_result.scala.html
build.sbt
conf/app.routes
conf/prod.routes
project/plugins.sbt

- play-frontend-hmrc to 1.9.0 to resolve reverse tabnapping concern for ur banner
- updated contact links with `rel` tag to resolve reverse tabnapping concern

[DDCE-2343][EH] Upgrading play-frontend-hmrc to 1.9.0

---

app/connectors/ResidencyStatusAPIConnector.scala
app/controllers/ChooseAnOptionController.scala
app/controllers/FileUploadController.scala
app/controllers/MemberDOBController.scala
app/controllers/MemberNameController.scala
app/controllers/MemberNinoController.scala
app/controllers/PageFlowController.scala
app/controllers/RasController.scala
app/controllers/RasResidencyCheckerController.scala
app/controllers/ResultsController.scala
app/controllers/SessionController.scala
app/services/AuditService.scala
app/views/choose_an_option.scala.html
app/views/govuk_wrapper.scala.html
build.sbt
project/plugins.sbt
test/controllers/RasResidencyCheckerControllerSpec.scala
test/services/AuditServiceSpec.scala
test/utils/RasTestHelper.scala
test/views/FileNotAvailableViewSpec.scala

Play 2.8 upgrade, general dependency updates and tidy up.

[DDCE-2025][EH] Play 2.8 upgrade

---

app/views/file_ready.scala.html
app/views/file_upload.scala.html
app/views/global_error.scala.html
app/views/govuk_wrapper.scala.html
app/views/no_results_available.scala.html
app/views/results_not_available_yet.scala.html
app/views/upload_result.scala.html
build.sbt

The 'submit a request for help' link was only redirecting to localhost, this is a fix to redirect to the correct environments

DDCE-2951 Fix the 'submit a request for help' link on ras-frontend

---

app/connectors/ResidencyStatusAPIConnector.scala
app/controllers/MemberDOBController.scala
app/forms/MemberDateOfBirthForm.scala
app/forms/MemberNameForm.scala
app/validators/DateValidator.scala
app/validators/NinoValidator.scala
build.sbt
conf/application-json-logger.xml
conf/application.conf
project/build.properties
project/plugins.sbt
test/forms/MemberDateOfBirthFormSpec.scala

- minor dependency upgrades,
- some warnings removed
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

[DDCE-3296] Play Frontend Dependency Upgrades

---

README.md
app/controllers/RasController.scala
app/controllers/ResultsController.scala
build.sbt
project/plugins.sbt
run_all_tests.sh
scalastyle-config.xml
test/controllers/RasControllerSpec.scala

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

DDCE-3674, WIP updating ras controller with added enrolments

---

app/services/TaxYearResolver.scala
build.sbt
test/services/SessionServiceSpec.scala
test/services/ShortLivedServiceSpec.scala

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).

DDCE-4011: Update Scala version to 2.13.10

---

README.md
app/controllers/ChooseAnOptionController.scala
app/controllers/ErrorController.scala
app/controllers/FileUploadController.scala
app/controllers/MemberDOBController.scala
app/controllers/MemberNameController.scala
app/controllers/MemberNinoController.scala
app/controllers/ResultsController.scala
app/models/RasDate.scala
app/services/SessionService.scala
app/views/file_upload.scala.html
build.sbt
conf/application.conf

- Add @CSPNonce.attr to Script tag 
- Upgrade sbt.version to 1.8.2 
- Upgrade other deps
- Add scalaOptions

DDCE-4168 - Enabled CSP Filter for Content Security Policy
